/* Shared domain types. Mirrors bot-crew/src/types.ts; the wire protocol lives at the bottom. */

export type Channel = 'app' | 'feishu' | 'wechat' | 'slack' | 'telegram' | 'discord' | 'whatsapp';
export type Autonomy = 'tell' | 'prepare' | 'do';
/** 通道的中文名，界面、提示词、给 bot 看的说明都用这一份。 */
export const CHANNEL_LABEL: Record<Channel, string> = { app: '应用内', feishu: '飞书', wechat: '企业微信', slack: 'Slack', telegram: 'Telegram', discord: 'Discord', whatsapp: 'WhatsApp' };
export type ConnectionKind = 'browser' | 'mcp' | 'api' | 'pay' | 'calendar' | 'mail';

export interface Connection {
  id: string;
  name: string;
  kind: ConnectionKind;
  status: 'ok' | 'expired' | 'error';
  note?: string;
}

export interface Routine {
  id: string;
  title: string;
  schedule: string;
  enabled: boolean;
  lastRun?: number;
  /** 结果发到哪几处：'app' 是应用内提醒，其余是这个 bot 在的 IM。不填 = 它在的地方都发。 */
  channels?: Channel[];
}

export interface Bot {
  id: string;
  name: string;
  glyph: string;
  tagline: string;
  /** agent.md：它的职责与工作流程（做什么、怎么做、什么之前要问） */
  role: string;
  /** soul.md：人设——性格、说话风格、待人方式 */
  soul: string;
  channels: Channel[];
  connections: Connection[];
  autonomy: Autonomy;
  viewOfYou: string[];
  skills: string[];
  routines: Routine[];
  notify: boolean;
  pinned: boolean;
  avatarUrl?: string;
  avatarSeed?: string;
  /** 外观描述（bot 自己用 configure 改头像时给的），生成头像时带进提示词 */
  avatarLook?: string;
  createdAt: number;
  /** server-only: the bot's private chat with the user on each IM it is connected to, e.g. { telegram: '<chatId>' }; learned from the first message there */
  bindings?: Partial<Record<Channel, string>>;
  /** this bot's own account on each IM (it is its own bot there, with its own credentials in config.json): live status for the App */
  im?: Partial<Record<Channel, ImLink>>;
  /** parts of the identity still being generated by models; UI shows placeholders */
  generating?: { identity?: boolean; avatar?: boolean };
  /** integrations (by id) this bot is allowed to use */
  integrationIds?: string[];
  /** self-builds in progress (build tool) */
  building?: BuildJob[];
  /** 成长动线：这个 bot 从诞生起每一次变化，按时间排 */
  growth?: GrowthEvent[];
  /** 产品自带的角色：steward = 管家，负责把 bot 们安顿到另一台机器并照看它 */
  kind?: 'steward';
  /** 正在值守的长程任务（vigil 工具）；持久化，重启后继续 */
  vigil?: Vigil;
  /** 它自己的电脑（云机器上的一个桌面，用户在 App 里能实时看到屏幕）；没有这个字段 = 从未开过机 */
}

/** A bot's own computer: a virtual display on the machine the bots run on, with a browser the bot drives. */
/** The one computer all bots share on the machine they run on (desktop.ts): a desktop with a browser, one tab per bot. */
export interface Computer {
  state: 'off' | 'starting' | 'on' | 'error';
  note?: string;
  since?: number;
  /** last time any bot drove it or someone watched it */
  lastUsed?: number;
  /** bots that drove it in the last couple of minutes */
  users?: string[];
}

export interface Vigil {
  goal: string;
  watching: string;
  /** how to observe; absent = a plain loop that just nudges the bot each interval */
  check?: { kind: 'machine' | 'http'; target: string; label: string };
  everyMs: number;
  startedAt: number;
  ticks: number;
  maxTicks: number;
  nextAt: number;
  /** signature of the last check result, to notice changes */
  lastSig?: string;
  /** the vigil card in the thread */
  messageId?: string;
}

export type GrowthKind =
  | 'born' | 'identity' | 'renamed' | 'instructions' | 'soul' | 'evolved'
  | 'skill' | 'skill_removed' | 'library' | 'memory' | 'forgot'
  | 'routine' | 'routine_removed' | 'connection' | 'disconnected' | 'channel' | 'group';
export interface GrowthEvent {
  id: string;
  ts: number;
  kind: GrowthKind;
  /** 一句话，里面用【】包住对象名，界面会高亮 */
  text: string;
}

/** What a bot can rebuild about itself with the build tool. */
export type BuildAspect = 'soul' | 'instructions' | 'skill' | 'memory';
/** An in-flight self-build; shown in the UI as "<aspect> building…" while it runs. */
export interface BuildJob {
  id: string;
  aspect: BuildAspect;
  label: string;
  since: number;
  skill?: string;
}

export type IntegrationKind = 'mcp' | 'channel' | 'agent' | 'shell';
/** External coding / general agents a bot can delegate to. */
export type AgentId = 'claude-code' | 'codex' | 'hermes' | 'opencode' | 'openclaw';
export const AGENT_IDS: AgentId[] = ['claude-code', 'codex', 'hermes', 'opencode', 'openclaw'];
export type IntegrationStatus = 'ok' | 'error' | 'off' | 'connecting';

/**
 * Something a bot can be granted:
 *   mcp      an MCP server (data, platforms, canvases…); its tools are registered on the bot
 *   channel  an IM the bot can live in
 *   agent    an external coding agent (Claude Code, Codex…) the bot can delegate to as a tool
 *   shell    pi's bash tool, confined to the bot's workspace
 */
export interface Integration {
  id: string;
  kind: IntegrationKind;
  name: string;
  status: IntegrationStatus;
  note?: string;
  createdAt: number;
  // mcp
  transport?: 'stdio' | 'http';
  command?: string;
  args?: string[];
  env?: Record<string, string>;
  /** http transport: request headers, `${KEY}` placeholders filled from env at connect time (e.g. Authorization: Bearer ${FAL_KEY}) */
  headers?: Record<string, string>;
  url?: string;
  tools?: { name: string; description?: string; write?: boolean }[];
  /** built-in connector id (gmail, google-calendar…); tools come from connectors.ts, not an MCP process */
  connector?: string;
  /** the signed-in account, e.g. an email */
  account?: string;
  // channel
  channel?: Channel;
  // agent
  agent?: AgentId | 'custom';
  available?: boolean;
  /** the agent can be driven over ACP (streaming, permissions, persistent session); else one-shot CLI */
  acp?: boolean;
  /** how to sign in when the agent reports it is not authenticated */
  loginHint?: string;
  /** the agent is not on this machine but on the user's computer (its name), which lends it while its EverBot is open */
  viaHost?: string;
  /** extra CLI args for the agent runner */
  agentArgs?: string[];
  /** private to one bot (its own computer's browser tools): not offered to other bots, not listed as a shared connection */
  owner?: string;
}

export type TodoStatus = 'open' | 'doing' | 'waiting' | 'blocked' | 'done';

/**
 * 这条事项是怎么来的：谁交办的、用户从哪个入口说的、在哪条会话里。建的时候由运行时快照，
 * 模型填不了也改不了；之后不随更新变化（「最近一次从哪推进的」是另一回事，现在不记）。
 */
export interface TodoOrigin {
  /** 谁交办的：用户、群里的同事、例行任务、系统事件 */
  by: 'user' | 'bot' | 'routine' | 'system';
  /** 用户是从哪个入口说的话；by 不是 user 时没有 */
  via?: Channel;
  /** by 是 bot 时，交办的那位同事 */
  fromBotId?: string;
  /** 在哪条会话里交办的：bot:X 私聊 ｜ matter:M 群聊 */
  threadId: ThreadId;
  /** 触发它的那条消息（用户说的话），用来跳回原文 */
  messageId?: string;
  at: number;
}

export interface Todo {
  id: string;
  botId: string;
  matterId?: string;
  title: string;
  status: TodoStatus;
  summary?: string;
  result?: string;
  createdAt: number;
  updatedAt: number;
  fromMessageId?: string;
  /** 怎么来的：谁交办、哪个入口、哪条会话。老数据没有。 */
  origin?: TodoOrigin;
}

export type PendingKind = 'confirm' | 'clarify' | 'blocked';

export interface PendingOption {
  id: string;
  label: string;
  hint?: string;
  primary?: boolean;
}

export interface Pending {
  id: string;
  botId: string;
  threadId: ThreadId;
  /** 从哪个 IM 发起的；有值且不是 app 的，只回到那个 IM，不进 App 窗口 */
  via?: Channel;
  matterId?: string;
  todoId?: string;
  kind: PendingKind;
  title: string;
  detail?: string;
  amount?: number;
  options: PendingOption[];
  messageId: string;
  createdAt: number;
  resolved?: { at: number; choice: string };
}

export interface Action {
  id: string;
  botId: string;
  matterId?: string;
  todoId?: string;
  ts: number;
  text: string;
  undoable?: boolean;
  undone?: boolean;
}

export interface Matter {
  id: string;
  title: string;
  date?: string;
  summary: string;
  ownerBotId: string;
  participantBotIds: string[];
  tools: string[];
  status: 'active' | 'done';
  notify: boolean;
  pinned: boolean;
  createdAt: number;
  /** the IM group this 群聊 mirrors, e.g. { feishu: '<chat_id>' }: created when the user pulls one of our bots into a group there */
  bindings?: Partial<Record<Channel, string>>;
}

/** A bot's connection to one IM. `account` is what the bot is called over there. */
export interface ImLink {
  status: 'ok' | 'off' | 'error' | 'connecting';
  note?: string;
  account?: string;
}

export type Card =
  | { type: 'confirm'; pendingId: string; title: string; sub: string; amount: number }
  | { type: 'options'; pendingId: string; options: { id: string; label: string; hint: string; price?: string }[] }
  | { type: 'blocked'; pendingId: string; title: string; sub: string }
  | { type: 'secrets'; integrationId: string; title: string; fields: { key: string; label: string; hint?: string; secret?: boolean }[]; help?: { url?: string; urlLabel?: string; steps?: string[] }; done?: boolean }
  /** 机器卡：管家发的。connect = 用户填 IP / 账号 / 密码，本机连上并存进凭据；run = 管家在那台机器上执行的一条命令及其输出；move = 把 bot 们搬到那台机器。密码只到服务端，bot 看不到。 */
  | {
      type: 'machine';
      stage: 'connect' | 'run' | 'move';
      title: string;
      /** connect: 默认登录用户名 */
      user?: string;
      state: 'idle' | 'running' | 'done' | 'error';
      log?: string[];
      error?: string;
      /** connect 成功后的机器体检 */
      summary?: string[];
      /** run: 执行的命令和退出码 */
      command?: string;
      exit?: number;
      /** move: 搬去哪 */
      target?: { url: string; name: string; bots: number };
      progress?: { sent: number; total: number };
    }
  /** 外部 agent 执行卡：bot 把任务交给了 Claude Code / Codex / Hermes / OpenCode / OpenClaw，这里实时显示它在做什么 */
  | {
      type: 'agent_run';
      agent: string;
      name: string;
      title: string;
      mode: 'acp' | 'cli';
      state: 'running' | 'done' | 'error';
      /** 工具调用与阶段性输出，一行一条 */
      log?: string[];
      /** 最终回复（截断） */
      output?: string;
      error?: string;
      /** 等用户拍板的权限请求数 */
      asked?: number;
      /** 在用户的电脑上运行（电脑名）：agent 装在电脑上，经本机转接调用 */
      viaHost?: string;
    }
  /** 值守卡：bot 正在盯一个长程任务（vigil 工具），系统按间隔检查、有变化才叫醒它 */
  | {
      type: 'vigil';
      goal: string;
      watching: string;
      everyS: number;
      checkLabel?: string;
      state: 'running' | 'stopped';
      ticks: number;
      lastAt?: number;
      lastOk?: boolean;
      last?: string;
      reason?: string;
    }
  | { type: 'connect'; connector: string; name: string; blurb: string; url: string; integrationId: string; done?: boolean; account?: string; failed?: string; expired?: boolean };

export type ReceiptKind = 'created' | 'updated' | 'closed' | 'reply';

/** A deliverable the bot produced in its workspace, served read-only at `url`. */
export interface FileRef {
  name: string;
  /** path relative to the bot's directory, e.g. workspace/report.html */
  path: string;
  /** which bot's directory `path` is under */
  botId?: string;
  size: number;
  mime: string;
  /** server-relative: /files/<botId>/<path>; the client prefixes the runtime it is connected to */
  url: string;
  /** the exact text the bot used to refer to it, so the client can render the file in place */
  mention?: string;
}

export interface Message {
  id: string;
  threadId: ThreadId;
  author: 'user' | 'bot' | 'system';
  botId?: string;
  text: string;
  ts: number;
  files?: FileRef[];
  card?: Card;
  todoId?: string;
  receipt?: { kind: ReceiptKind; text: string; todoId?: string };
  via?: Channel;
  /** 这条只发到这几处（例行任务指定了通道时）。不填 = 照常：应用 + 这个 bot 在的每个 IM。 */
  to?: Channel[];
  mentions?: string[];
  status?: string;
}

export type ThreadId = `bot:${string}` | `matter:${string}`;
export const botThread = (botId: string): ThreadId => `bot:${botId}`;
export const matterThread = (matterId: string): ThreadId => `matter:${matterId}`;
export const parseThread = (t: ThreadId) => {
  const i = t.indexOf(':');
  return { kind: t.slice(0, i) as 'bot' | 'matter', id: t.slice(i + 1) };
};

export interface Toast {
  botId: string;
  text: string;
  threadId: ThreadId;
}

/** A skill document: pi SKILL.md (frontmatter + markdown), addressed by its display name. */
export interface SkillDoc {
  name: string;
  slug: string;
  description: string;
  body: string;
  updatedAt: number;
  generating?: boolean;
  /** Set when the skill was mounted from the library: library slug, category and upstream source. */
  library?: string;
  category?: string;
  source?: string;
  /** Pool slugs this manual was written on top of, filled in by the runtime, not by the bot. */
  needs?: string[];
}

/** What a bot can equip itself with, from the pool (crew-server/library + manifest, mirrored to ~/.crew/library). */
export type LibraryKind = 'skill' | 'mcp' | 'assets';

/**
 * One thing a bot can equip itself with. A manual, an external tool set (an MCP server, or a platform behind the
 * product's OAuth service — both end up as tools on the bot; only the authorization differs), a pack of assets.
 * The differences are in how they are installed, not in how they are found, so they share one index and one search.
 */
export interface LibraryEntry {
  slug: string;
  title: string;
  category: string;
  description: string;
  tags: string[];
  source?: string;
  license?: string;
  /** what kind of thing this is; absent in old data means a skill */
  kind?: LibraryKind;
  /** kind=skill: the manual's SKILL.md on this machine — readable (read tool) without mounting it */
  path?: string;
  /** kind=mcp: how to start it and what it needs. Absent when the tools come through `service`. */
  mcp?: {
    transport: 'stdio' | 'http';
    command?: string;
    args?: string[];
    url?: string;
    /** package to install into the product's own prefix first, so the server does not download itself on every start */
    npm?: string;
    pip?: string;
    /** credentials the user has to bring; asked for with a card, never through the conversation */
    env?: { key: string; label: string; hint?: string; secret?: boolean }[];
    help?: { url?: string; urlLabel?: string; steps?: string[] };
    /** one line about what its tools do, for search and for the bot */
    tools?: string;
    /** http: headers to send, with `${ENV_KEY}` placeholders for the card's values */
    headers?: Record<string, string>;
  };
  /** kind=mcp, hosted behind the product's OAuth connector service: the toolkit slug. Authorization is a click on a card, not a key. */
  service?: string;
  /** kind=assets: a pack to download into the workspace */
  assets?: { url: string; howto?: string };
}

/** 全局偏好：跟着这套 bot 走，不是某个浏览器的设置 */
export interface CrewSettings {
  /** bot 用什么语言说话和写东西：界面语言的代码（zh、en、ja…），或 auto = 跟着用户当时说的语言 */
  language?: string;
  /** 用户所在时区（IANA 名，App 上报）。例行任务的时间按它算：云机器本身跑在 UTC 上。 */
  timezone?: string;
}

export interface Snapshot {
  runtime?: RuntimeInfo;
  settings?: CrewSettings;
  /** the shared computer's state; absent on a runtime that cannot host one */
  computer?: Computer;
  bots: Bot[];
  matters: Matter[];
  todos: Todo[];
  pendings: Pending[];
  actions: Action[];
  messages: Message[];
  sharedProfile: string[];
  skills?: SkillDoc[];
  library?: LibraryEntry[];
  /** threadId -> bot ids currently mid-turn (ephemeral, not persisted) */
  typing?: Record<string, string[]>;
  /** 升级状态：这台电脑上的代码 vs 正在跑的代码 */
  upgrade?: UpgradeStatus;
  integrations: Integration[];
}

/* ---------------- wire protocol ---------------- */

export type ClientMessage =
  | { type: 'user_message'; id?: string; threadId: ThreadId; text: string; via?: Channel; files?: FileRef[] }
  | { type: 'migrate_to'; url: string; token: string; force?: boolean }
  | { type: 'remote_install'; host: string; user: string; password?: string; domain?: string }
  | { type: 'migrate_from'; url: string; token: string }
  /** 叫管家出来：确保管家 bot 存在，并替用户发出第一句话 */
  | { type: 'steward'; intent: 'move_out' }
  /** 连接卡提交：本机 ssh 连上那台机器，密码存进本机凭据，体检结果写回卡片并告知管家 */
  | { type: 'machine_connect'; messageId: string; host: string; user: string; password?: string; port?: number }
  /** 机器卡（move）点了「搬过去」 */
  | { type: 'machine_move'; messageId: string }
  | { type: 'draft_message'; id?: string; text: string }
  | { type: 'pending_choice'; pendingId: string; optionId: string }
  | { type: 'patch_bot'; id: string; patch: Partial<Bot> }
  | { type: 'patch_matter'; id: string; patch: Partial<Matter> }
  | { type: 'create_matter'; id?: string; title: string; summary?: string; memberIds: string[]; leadId: string }
  | { type: 'set_shared_profile'; lines: string[] }
  | { type: 'undo_action'; actionId: string }
  | { type: 'avatar'; botId: string; op: 'regen' | 'reset' | 'upload'; dataUrl?: string }
  | { type: 'delete_bot'; id: string }
  | { type: 'delete_matter'; id: string }
  | { type: 'patch_skill'; name: string; patch: { description?: string; body?: string } }
  | { type: 'mount_library_skill'; botId: string; slug: string }
  | { type: 'submit_secrets'; messageId: string; integrationId: string; values: Record<string, string> }
  /** 把一个 bot 接到某个 IM：在它的会话里发一张凭据卡（它在那个 IM 里是独立的机器人，凭据只进 config.json） */
  | { type: 'connect_channel'; botId: string; channel: Channel }
  /** 断开一个 bot 在某个 IM 上的账号：停桥、删凭据 */
  | { type: 'disconnect_channel'; botId: string; channel: Channel }
  /** 给 bot 的电脑开机 / 关机 */
  | { type: 'computer_power'; on: boolean }
  /** 升级到这台电脑上的最新代码（bot 在云机器上时，连那台一起升） */
  | { type: 'upgrade' }
  | { type: 'usage'; days?: number }
  | { type: 'set_settings'; patch: CrewSettings }
  | { type: 'add_integration'; integration: Pick<Integration, 'kind' | 'name' | 'transport' | 'command' | 'args' | 'url' | 'env' | 'agent' | 'agentArgs'> & { id?: string } }
  | { type: 'patch_integration'; id: string; patch: Partial<Integration> }
  | { type: 'remove_integration'; id: string }
  | { type: 'test_integration'; id: string }
  | { type: 'clear_thread'; threadId: ThreadId };

export type ServerMessage =
  | { type: 'migrated'; direction: 'to' | 'from'; url: string; bots?: number }
  | { type: 'migrate_progress'; sent: number; total: number }
  | { type: 'steward'; botId: string }
  /** bot 们已搬走：客户端切到那台机器（带上它的连接凭据）并刷新 */
  | { type: 'switch_runtime'; url: string; token: string; name?: string }
  | { type: 'remote_install_log'; line: string }
  | { type: 'remote_install_done'; code?: string; url?: string; error?: string }
  | { type: 'runtime'; runtime: RuntimeInfo }
  | { type: 'upgrade_status'; status: UpgradeStatus }
  | { type: 'upgrade_log'; line: string }
  | { type: 'upgrade_done'; error?: string; restarting?: boolean }
  | { type: 'usage'; report: UsageReport }
  | { type: 'snapshot'; state: Snapshot; mode: 'live' | 'fake' }
  | { type: 'message'; message: Message }
  | { type: 'message_patch'; id: string; patch: Partial<Message> }
  | { type: 'typing'; threadId: ThreadId; botId: string; on: boolean }
  | { type: 'todo'; todo: Todo }
  | { type: 'pending'; pending: Pending }
  | { type: 'action'; action: Action }
  | { type: 'bot'; bot: Bot }
  | { type: 'matter'; matter: Matter }
  | { type: 'shared_profile'; lines: string[] }
  | { type: 'settings'; settings: CrewSettings }
  | { type: 'toast'; toast: Toast }
  | { type: 'bot_created'; bot: Bot; draftId?: string }
  | { type: 'bot_deleted'; id: string }
  | { type: 'matter_deleted'; id: string }
  | { type: 'skill'; skill: SkillDoc }
  | { type: 'integration'; integration: Integration }
  | { type: 'integration_deleted'; id: string }
  | { type: 'thread_cleared'; threadId: ThreadId }
  | { type: 'error'; error: string };

/** What a client needs to know about the server it is talking to (see runtime.ts). */
export interface RuntimeInfo {
  instanceId: string;
  hostname: string;
  platform: string;
  home: string;
  botsDir: string;
  /** where the server code is installed (for commands the client tells the user to run) */
  serverDir: string;
  publicUrl: string;
  local: boolean;
  desktop: boolean;
  mode: 'active' | 'standby' | 'moved';
  movedTo?: string;
  version: string;
  startedAt: number;
  /** (remote runtime) the user's computer currently lending its agents: name and which agents it has */
  agentHost?: { name: string; agents: string[]; since: number };
  /** (signpost on the computer) the link that lends this computer's agents to the machine the bots moved to */
  hostLink?: 'connecting' | 'connected' | 'off' | 'no_token';
  /** this runtime can give each bot its own computer (a Linux desktop with a browser, watchable from the App) */
  desktops?: boolean;
  /** why not, when it cannot */
  desktopsNote?: string;
  /** fingerprint of the code this process is running (see version.ts) */
  build?: string;
  /** bots in the middle of a turn right now (an upgrade waits for them) */
  busy?: string[];
}

/** 用量：token 和花费，按 bot / 天 / 模型汇总（从每个 bot 的会话日志读出来，见 usage.ts） */
export interface UsageRow {
  input: number;
  output: number;
  cacheRead: number;
  cacheWrite: number;
  cost: number;
  calls: number;
}
export interface UsageReport {
  days: number;
  /** the earliest call counted, if any */
  since?: number;
  total: UsageRow;
  bots: (UsageRow & { botId: string; name: string })[];
  daily: (UsageRow & { day: string })[];
  models: (UsageRow & { model: string })[];
}

/** 升级：这台电脑上的代码、正在跑的代码、bot 所在机器上的代码，三者对不对得上（见 upgrade.ts） */
export interface UpgradeStatus {
  /** bot 在哪：这台电脑，还是搬去的那台机器 */
  target: 'local' | 'machine';
  /** 跑 bot 的那一端所在的提交 */
  running?: string;
  /** 仓库分支上最新的提交 */
  latest?: string;
  version: string;
  repo: string;
  branch: string;
  /** 这台电脑上有没提交的改动 */
  dirty?: boolean;
  upToDate: boolean;
  /** 现在为什么不能升 */
  blocked?: string;
  machineName?: string;
  busy?: boolean;
}
